### ISSUE TITLE
Differences from the paper

### ISSUE THREAD

**Issue by francqz31** [Wataru-Nakata/miipher#1]
Hello Author ,
I wanted to know what are the differences of this repo from the main paper (all differences) , Because I might be able to help to make it as close as possible to the original paper.
I believe miipher has 4 unique models which are (Non-Attentive Tacotron) And (w2v-bert) and (PnG-BERT) and (wavefit) and all of them are closed source. so what were the replacements for those. 
also you may inform me if I'm missing something.

Thanks in advance.

**Comment by Wataru-Nakata** [comment]
Thank you for having an interest on my work.
I will add a specific section regarding the differences from the paper on README. 
I'll let you know when it's done.
By the way, I think non-attentive tacotron on the paper is only used for the evaluation purpose.
Therefore, It is not a building block of Miipher in my understanding.

**Comment by francqz31** [comment]
oh yeah you are right 100% , non-attentive Tacotron serves as the neural TTS model that enables high quality synthesis when trained on the proposed restored speech data, demonstrating the effectiveness of the restoration approach. Its non-attentive nature allows it to learn from unaligned text and audio during training.

**Comment by francqz31** [comment]
I was just generalizing that everything involved in that paper is almost closed source. 
ok I will be waiting for the readme and try to push this implementation to maximum level 👍

**Comment by francqz31** [comment]
WaveFit vocoder is insanely good , it is 100% behind the astonishing quality of miipher , I have 2 Gan vocoders that almost the same quality as wavefit-5 , one is public and one is private (the private uses U-net too) , so I think the quality would 2x up just by having a strong vocoder and more datasets .

**Comment by francqz31** [comment]
we will see

**Comment by Wataru-Nakata** [comment]
I have added a specific section regarding the differences from the original paper. Please check it out. Feel free to reopen this issue if I'm missing something.

**Comment by francqz31** [comment]
@Wataru-Nakata amazing , ok so I think what is needed here is basically ablation study, 
🔴 I'm sure that LibriTTS-R and JVS corpus are as efficient as their proprietary data if not actually better , maybe adding 24khz VCTK would be pretty but I think leaving it as it is , is still more than enough.

🔴Noise dataset is the same not if even better by adding Slakh2100
so the data part is a pass I believe ✅

🔴 Speech ssl model: I keep reading i really don't find a massive difference at all between W2v-BERT XL and WavLM-large like that shouldn't effect the quality at all ?

🔴 But with PnG BERT and XPhoneBERT there might be something , after researching I found that ( PL-BERT claims to be better than mpbert , mpbert is comparable to png-bert and gives exactly the same performance not to mention Xphone never compared itself to any of these Berts ) so maybe try using PL-Bert ? , i know that XPhoneBERT  is Multilingual but miipher only showed that amazing  quality on english right ! 
https://github.com/yl4579/PL-BERT ,, The pre-trained PL-BERT on Wikipedia for 1M steps can be downloaded here
https://drive.google.com/file/d/19gzPmWKdmakeVszSNuUtVMMBaFYMQqJ7/view ,, if you used that and it made a difference in the quality then we certainly are headed to the right way !!

🔴Feature cleaner building block: also after researching for along time DF-Conformer is indeed better than conformer , and that might make a difference ,
i found 4 possible replacements for conformer
https://github.com/AlbertSebastain/RobustConformer
https://github.com/Miamoto/Conformer-NTM
https://github.com/burchim/EfficientConformer
https://github.com/tuanio/nextformer                   

🔴X-Vector model: spkrec-xvect-voxceleb is great but not sure if better than what they used , 
have you checked that out https://huggingface.co/nvidia/speakerverification_en_titanet_large that might be better than the above.

🔴 The vocoder part , hifigan is outdated tbh and is not suitable for this project , there have been way better vocoders like 
The best one in my opinion is this https://github.com/yl4579/HiFTNet , this one has almost ground truth quality and have Pre-Trained Models , i believe that this vocoder is the same as wavefit-5  , i also have a private vocoder that produces almost GT too. sorry if that was long but i will wait for your opinion too. :)

**Comment by Wataru-Nakata** [comment]
Thank you for insightful comments.
In my opinion, the use of LibriTTS-R is leading to poor performance.
I have noticed while listening thorough the speech clips of LibriTTS-R but there are some speeches which google's miipher has failed to restore.
I have around one thousand hours of japanese clean speech. I will try to retrain the model using that.
If that doesn't work, I will check the alternatives you have mentioned above. 
The computational resource I have is limited so I will try one by one.
It might take some time but please be patient.

**Comment by francqz31** [comment]
of course I will be patient 👍
oh really? I haven't downloaded LibriTTS-R I thought it was really really good as they advertise .
also but then you wouldn't have English speech data idk if that will effect it .
for you info the best English datasets that I can found are these ( you may listen to them if you want and decide if you want to include them)
1-http://www.openslr.org/109/
2-https://www.openslr.org/45/  
3-https://datashare.ed.ac.uk/handle/10283/2651
ok as you say if retraining by better data didn't make any huge difference,
I would recommend starting by PL-BERT instead of XPhoneBERT  , then the vocoder HiFTNet.
also if you want me to train any thing from my end I will.
ok I will be waiting patiently :)

**Comment by pranavmalikk** [comment]
@francqz31 do you have this special vocoder anywhere. I'm currently working on training wavefit with some help. Would be interested in hearing some samples from your private vocoder
