### ISSUE TITLE
new data training

### ISSUE THREAD

**Issue by cutekih** [Wataru-Nakata/miipher#5]
Hello. Can I use your git repo to train with my new language data?

**Comment by Wataru-Nakata** [comment]
Yes. it is absolutely possible! in fact, this repo contains everything you need to train your own miipher from scratch.
Please check out the configuration file first

**Comment by Wataru-Nakata** [comment]
This configuration file should give you some insights on how to start training miipher with your own data
https://github.com/Wataru-Nakata/miipher/blob/main/examples/configs/config.yaml
