### ISSUE TITLE
About the dataset 

### ISSUE THREAD

**Issue by jjjanicehuang** [Wataru-Nakata/miipher#6]
May I ask how many audio files were used for the LibriTTS, JVS, and noise datasets respectively?

**Comment by Wataru-Nakata** [comment]
Thank you for your interest in my work.
Please check the corresponding dataset website for details about the dataset
[LibriTTS-R](https://arxiv.org/abs/2305.18802)
[JVS](https://arxiv.org/abs/1908.06248)
[TAU Urban](https://zenodo.org/records/4477542)
